services:
  plc:
    build:
      context: .
      dockerfile: cmd/plc-mirror/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    image: uabluerail/plc-mirror
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      PLC_METRICS_PORT: '8080'
      PLC_POSTGRES_URL: "${PLC_POSTGRES_URL}"
    ports:
      - "0.0.0.0:11004:8080"
    command: [ "--log-level=0" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 30s
      timeout: 5s
      retries: 30
      start_period: 12h
      start_interval: 15s
